### ISSUE TITLE
Add an object of a player on the map

### ISSUE THREAD

**Issue by AggelosTh** [AggelosTh/pygame_fantasy#1]
On our first attempt we managed to draw a map.
![image](https://github.com/user-attachments/assets/3859fff8-a173-4bce-bdce-6353a2fe26f0)

Next we will add a player object on the map and try to move it on it.

**Comment by antarga** [comment]
With the power of the cards we will do it!

**Comment by AggelosTh** [comment]
Resolved [here](https://github.com/AggelosTh/pygame_fantasy/pull/3)
